### PR TITLE
SWARM-1828: a bit more info on the page

### PR DESCRIPTION
**Pull request by michalszynkiewicz**

### CODE REVIEW

**Review by heiko-braun — APPROVED** [review]

**Comment by Ladicek** [comment]
Did you look at https://github.com/snowdrop/spring-boot-cache-booster or https://github.com/openshiftio-vertx-boosters/vertx-cache-booster? Ideally, the pages would be pretty similar.

**Comment by michalszynkiewicz** [comment]
@Ladicek IMO Spring Boot page is not ready, it doesn't have an indicator if there's a value in the cache nor a description.
I wasn't aware there's a vertx booster, it looks rather complete. I can align to what they have.

**Comment by Ladicek** [comment]
The Spring Boot booster passes the same set of tests the Swarm one does, so the API is all there. If the webpage doesn't satisfy all the requirements, then that sounds like a bug -- thanks for info, I'll look into that.

**Comment by michalszynkiewicz** [comment]
@Ladicek I reused the page from Vert.x and accidentally merged the change, sorry.

Thank you for the review. The page looks exactly as Vert.x one now. The only two differences are different title and the interval on which the page checks if the value is in cache.

**Comment by Ladicek** [comment]
Cool, thanks!

**Pull request merged**
